AWSTemplateFormatVersion: 2010-09-09
Resources:
  capstonecloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: ""
        Origins:
          - Id: udacitydevops5-LoadBalancer-1314534807.us-east-1.elb.amazonaws.com
            DomainName: udacitydevops5-LoadBalancer-1314534807.us-east-1.elb.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          TargetOriginId: udacitydevops5-LoadBalancer-1314534807.us-east-1.elb.amazonaws.com
          ViewerProtocolPolicy: "allow-all"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
Outputs:
  CloudFrontDistributionURL:
    Description: URL of the CloudFront distribution
    Value: !Sub "https://${capstonecloudfrontdistribution}.cloudfront.net"